// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://renayjdbegjhjgazrzcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlbmF5amRiZWdqaGpnYXpyemNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Nzk4OTEsImV4cCI6MjA2MjA1NTg5MX0.Y65S7daBjAc5_IYHfgNNfObyD9f4zcEDTHk8AYHdfoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);